<?php
/**
 * Plugin Name:       External files from AWS S3-compatible platforms in Media Library
 * Description:       Extends External files in Media Library for usage AWS S3-compatible platforms.
 * Requires at least: 6.2
 * Requires PHP:      8.1
 * Requires Plugins:  external-files-in-media-library
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       external-files-from-aws-s3
 *
 * @package external-files-from-aws-s3
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// do nothing if PHP-version is not 8.1 or newer.
if ( PHP_VERSION_ID < 80100 ) { // @phpstan-ignore if.alwaysFalse,smaller.alwaysFalse
	return;
}

use ExternalFilesFromAwsS3\Plugin\Init;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// bail if "External files in Media Library" is not active.
if ( ! Init::get_instance()->is_parent_plugin_active() ) {
	return;
}

// get plugin-path.
const EFMLAWSS3_PLUGIN = __FILE__;

// set the version.
const EFMLAWSS3_PLUGIN_VERSION = '1.0.0';

// initialize plugin.
Init::get_instance()->init();
